# Server Configuration
server.port=8980
spring.application.name=power-monitor

# CORS Configuration
cors.allowed-origins=http://localhost:4201
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*

# CSV Data Configuration
#data.csv.path=classpath:data/power-sample.csv
data.csv.path=data/power-sample.csv

# WebSocket Configuration
websocket.endpoint=/ws
websocket.topic=/topic/realtime
websocket.app-prefix=/app

# Logging
logging.level.com.bigdata.power_monitor=DEBUG
logging.level.org.springframework.web=INFO

# Trino JDBC datasource
spring.datasource.url=jdbc:trino://localhost:8082/hive/energy
spring.datasource.driver-class-name=io.trino.jdbc.TrinoDriver

# Optional: set user if needed
spring.datasource.username=trino_user

# If your Trino doesn?t require a password leave blank or omit
# spring.datasource.password=

# Disable datasource initialization (no schema migrations)
spring.jpa.defer-datasource-initialization=true
